@startuml OSMI Design
class DisplayTask {
  - void update()
}
' class ControlWatchdogTask {}
interface FluidController {
  +  void start()
  +  void pause()
  +  void reset()

  +  void reverse()
  +  float getVolumeDelivered()

  +  float setBolusRate(float flowRate, float bolusDosage)
  +  float setDosageRate(float flowRate, float finalDosage)

  + int getStatus()


}

interface FluidDriver {
  +void enable()
  +void disable()

  +void setVelocity(float mmPerSecond)
  +float getDistanceMM()

  +void setDirection(direction_t direction)

  +int getStatus()
  +bool occlusionDetected()

}

FluidController -> FluidDriver

class Team11Controller {
  - float syringeVolumePerStep
}

class Esp32PwmSpiDriver {
  - unsigned long long travelMaximum
  - unsigned long stepOverflowCount
  - void initPWM()
  - void initPulseCounter()
}

' DisplayTask -[hidden]--> ControlWatchdogTask

Team11Controller -UP-|> FluidController
Esp32PwmSpiDriver -UP-|> FluidDriver

' ControlWatchdogTask -> "*" FluidController
DisplayTask -RIGHT-> "*" FluidController
@enduml